### ISSUE TITLE
显卡注入的问题

### ISSUE THREAD

**Issue by ghost** [1and1get2/CP65S#2]
大大，我的笔记本（同Z7M-I78172D1）可能与你的屏幕不同，直接使用你的EDID会导致开机进度条走到三分之二后黑屏。关掉EDID注入，便会进入系统后花屏，合上盖子再打开，会导致闪屏。我更换了ig-platform-id为0x0a260000后，进入系统会花屏，开关一下盖子之后才才正常。请问，我该如何修改我的EDID才能注入正常？谢谢

**Comment by hereisderek** [comment]
http://bbs.pcbeta.com/viewthread-1762479-1-1.html
我的edid Horizontal Sync Pulse Width 默认是32，我改成100就不会花屏了。而且我用了DisplayVendorID-30e4 文件增加了额外的分辨率支持，你可以试一下
https://github.com/1and1get2/CP65S/tree/master/VIDEO_PORTS_HDMI_DP/edid_fixed/DisplayVendorID-30e4
文件夹复制到 /System/Library/Displays/Contents/Resources/Overrides/
