### ISSUE TITLE
Thank you very much for sharing your EFI.

### ISSUE THREAD

**Issue by ghost** [1and1get2/CP65S#4]
Hi,I use your EFI in my laptop(Z7M-I78172D1),it seems everything works ok except the HD4600.so i change your EFI's EDID, use my own EDID, and i also change ig-platform-id to 0x0a260000, therefore my display works good.
thanks you very much for sharing your EFI.
Could I share your EFI to bbs.pcbeta.com?

**Comment by hereisderek** [comment]
我懂中文的。。   
可以啊

我建了个群 399630130，你要是有兴趣可以加一下
ig-platform-id的话，我没用过你的那个，如果换的话可能需要改dsdt。
你看下你的屏幕亮度工作正常么

**Comment by ghost** [comment]
啊啊哈哈，谢谢老哥。我就说嘛，肯定是中国人

**Comment by ghost** [comment]
你那个群需要群主邀请啊。可以邀请一下我吗。QQ1016869375

**Comment by yyuueexxiinngg** [comment]
群满了。。尴尬QAQ

**Comment by hereisderek** [comment]
你qq多少 我拉你好了

你是从哪里找到我的

**Comment by yyuueexxiinngg** [comment]
> 你qq多少 我拉你好了 你是从哪里找到我的

QQ: 1593565713
直接在Github上搜到的，后来发现贴吧那个大佬也是你2333
